# Generated by Django 4.2.2 on 2023-07-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
